app/src/Entity/Addresses.php
<?php

namespace App\Entity;

use App\Repository\AddressesRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AddressesRepository::class)]
class Addresses
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $num = null;

    #[ORM\Column(length: 50)]
    private ?string $road_type = null;

    #[ORM\Column(length: 255)]
    private ?string $road_name = null;

    #[ORM\Column]
    private ?int $zip = null;

    #[ORM\Column(length: 100)]
    private ?string $city = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNum(): ?int
    {
        return $this->num;
    }

    public function setNum(int $num): self
    {
        $this->num = $num;

        return $this;
    }

    public function getRoadType(): ?string
    {
        return $this->road_type;
    }

    public function setRoadType(string $road_type): self
    {
        $this->road_type = $road_type;

        return $this;
    }

    public function getRoadName(): ?string
    {
        return $this->road_name;
    }

    public function setRoadName(string $road_name): self
    {
        $this->road_name = $road_name;

        return $this;
    }

    public function getZip(): ?int
    {
        return $this->zip;
    }

    public function setZip(int $zip): self
    {
        $this->zip = $zip;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }
}

app/src/Entity/Bills.php
<?php

namespace App\Entity;

use App\Repository\BillsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BillsRepository::class)]
class Bills
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $firstName = null;

    #[ORM\Column(length: 255)]
    private ?string $lastName = null;

    #[ORM\Column]
    private ?int $address_id = null;

    #[ORM\Column(length: 255)]
    private ?string $rental_name = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: '0')]
    private ?string $pool_adult_pu = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: '0')]
    private ?string $pool_kid_pu = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: '0')]
    private ?string $ts_adult_pu = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: '0')]
    private ?string $ts_kid_pu = null;

    #[ORM\Column]
    private ?int $nb_adult = null;

    #[ORM\Column]
    private ?int $nb_kid = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $check_in = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $check_out = null;

    #[ORM\Column]
    private ?int $pool_adult_nb = null;

    #[ORM\Column]
    private ?int $pool_kid_nb = null;

    #[ORM\Column]
    private ?int $product_id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getAddressId(): ?int
    {
        return $this->address_id;
    }

    public function setAddressId(int $address_id): self
    {
        $this->address_id = $address_id;

        return $this;
    }

    public function getRentalName(): ?string
    {
        return $this->rental_name;
    }

    public function setRentalName(string $rental_name): self
    {
        $this->rental_name = $rental_name;

        return $this;
    }

    public function getPoolAdultPu(): ?string
    {
        return $this->pool_adult_pu;
    }

    public function setPoolAdultPu(string $pool_adult_pu): self
    {
        $this->pool_adult_pu = $pool_adult_pu;

        return $this;
    }

    public function getPoolKidPu(): ?string
    {
        return $this->pool_kid_pu;
    }

    public function setPoolKidPu(string $pool_kid_pu): self
    {
        $this->pool_kid_pu = $pool_kid_pu;

        return $this;
    }

    public function getTsAdultPu(): ?string
    {
        return $this->ts_adult_pu;
    }

    public function setTsAdultPu(string $ts_adult_pu): self
    {
        $this->ts_adult_pu = $ts_adult_pu;

        return $this;
    }

    public function getTsKidPu(): ?string
    {
        return $this->ts_kid_pu;
    }

    public function setTsKidPu(string $ts_kid_pu): self
    {
        $this->ts_kid_pu = $ts_kid_pu;

        return $this;
    }

    public function getNbAdult(): ?int
    {
        return $this->nb_adult;
    }

    public function setNbAdult(int $nb_adult): self
    {
        $this->nb_adult = $nb_adult;

        return $this;
    }

    public function getNbKid(): ?int
    {
        return $this->nb_kid;
    }

    public function setNbKid(int $nb_kid): self
    {
        $this->nb_kid = $nb_kid;

        return $this;
    }

    public function getCheckIn(): ?\DateTimeInterface
    {
        return $this->check_in;
    }

    public function setCheckIn(\DateTimeInterface $check_in): self
    {
        $this->check_in = $check_in;

        return $this;
    }

    public function getCheckOut(): ?\DateTimeInterface
    {
        return $this->check_out;
    }

    public function setCheckOut(\DateTimeInterface $check_out): self
    {
        $this->check_out = $check_out;

        return $this;
    }

    public function getPoolAdultNb(): ?int
    {
        return $this->pool_adult_nb;
    }

    public function setPoolAdultNb(int $pool_adult_nb): self
    {
        $this->pool_adult_nb = $pool_adult_nb;

        return $this;
    }

    public function getPoolKidNb(): ?int
    {
        return $this->pool_kid_nb;
    }

    public function setPoolKidNb(int $pool_kid_nb): self
    {
        $this->pool_kid_nb = $pool_kid_nb;

        return $this;
    }

    public function getProductId(): ?int
    {
        return $this->product_id;
    }

    public function setProductId(int $product_id): self
    {
        $this->product_id = $product_id;

        return $this;
    }
}

app/src/Controller/BillsController.php
<?php

namespace App\Controller;

use App\Entity\Bills;
use App\Repository\AddressesRepository;
use App\Repository\BillLinesRepository;
use App\Repository\BillsRepository;
use App\Repository\BookingsRepository;
use Cassandra\Date;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Bundle\SnappyBundle\Snappy\Response\PdfResponse;
use Knp\Snappy\Pdf;

#[Route('/admin')]
class BillsController extends AbstractController
{
    private BillLinesRepository $linesRepo;
    private BookingsRepository $bookingRepo;
    private BillsRepository $billRepo;
    private AddressesRepository $adressRepo;

    public function __construct(BillLinesRepository $linesRepo,
                                BookingsRepository $bookingRepo,
                                BillsRepository $billRepo,
                                AddressesRepository $adressRepo)
    {
        $this->linesRepo   = $linesRepo;
        $this->bookingRepo = $bookingRepo;
        $this->billRepo    = $billRepo;
        $this->adressRepo  = $adressRepo;
    }

    /**
     * Liste de toutes les factures
     */
    #[Route('/billList', name: 'app_bills')]
    public function index(): Response
    {

        $bills = $this->billRepo->findAll();

        return $this->render('admin/bills_list.html.twig', [
            'bills' => $bills,
        ]);
    }

    /**
     * Donne le details de la facture
     */
    #[Route('/billDetails/{id}', name: 'bill_details', requirements: ['id' => '\d+'])]
    public function details($id): Response
    {
        $bill = $this->billRepo->find($id);
        $address = $this->adressRepo->find($bill->getAddressId());
        $nb_days = ($bill->getCheckOut()->getTimestamp() - $bill->getCheckIn()->getTimestamp()) / (60*60*24);

        return $this->render('bills/content.html.twig', [
            'bill' => $bill,
            'address' => $address,
            'days' => $nb_days,
        ]);
    }

    /**
     * Génere la facture
     */
    #[Route('/billGenerate/{id}', name: 'bill_generate', requirements: ['id' => '\d+'])]
    public function generate(ManagerRegistry $manager, Pdf $pdf, $id = 0): Response
    {
        //date
        $date = date(DATE_ATOM,mktime(time()));

        // si l'id de la réservation existe
        if($id > 0) {
            // On récupère la réservation
            $booking = $this->bookingRepo->find($id);

            //On récupère le produit (mobile-home, emplecement ou caravane)
            $product = $booking->getProductId();

            //On récupère le client
            $client = $booking->getClientId();

            //On récupère son adresse
            $address = $client->getAddressId();

            //On récupère les lignes de facturation
            $lines = $this->linesRepo->findAllLines($id);

            //On récupère la facture déjà générée ou on en crée une nouvelle
            $bill = $this->billRepo
                    ->findOneBy([
                        'product_id' => $product->getId(),
                        'check_in' => $booking->getCheckIn()
                    ]) ?? new Bills() ;

            $rental     = $lines[0];
            $poolAdult  = $lines[1];
            $poolKid    = $lines[2];
            $tsAdult    = $lines[3];
            $tsKid      = $lines[4];
            //création de la facture

                //identification du client

            //Enregistrement de la facture
            $em = $manager->getManager();
            $em->persist($bill);
            $em->flush();

            $pdf->generateFromHtml(
                $this->renderView(
                    'bills/pdf_template.html.twig',
                    [
                        'rental' => $rental,
                        'poolAdult' => $poolAdult,
                        'poolKid' => $poolKid,
                        'tsAdult' => $tsAdult,
                        'tskid' => $tsKid,
                    ]),
                    'bills/bill_'.$id.'.pdf'
            );
        }
        //return $this->redirectToRoute('bookingsList');
        dump($rental);
        return $this->render('bills/pdf_template.html.twig',
            [
                'rental' => $rental,
                'poolAdult' => $poolAdult,
                'poolKid' => $poolKid,
                'tsAdult' => $tsAdult,
                'tskid' => $tsKid,
            ]
        );
    }

}

app/templates/bills/content.html.twig
{% extends 'base.html.twig' %}
{% block title %}Détail de la réservation{% endblock %}
{% block header %} {{ include('parts/_header.html.twig') }} {% endblock %}
{% block body %}
    <h2>Facture du séjour</h2>

    <div>
        <h4>Hébergement</h4>
        <div>{{ bill.rentalName }}</div>
    </div>

    <div>
        <h4>Client</h4>
        <div>
            <p>{{ bill.firstname }} {{ bill.lastname }}</p>
            <p>{{ address.num }} {{ address.roadType }}  {{ address.roadName }}</p>
            <p>{{ address.zip}} {{ address.city }}</p>
            <p>{{ address.country }}</p>
        </div>
    </div>

    <div>
        <h4>Prestations</h4>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Label</th>
                    <th scope="col">Quantité</th>
                    <th scope="col">Prix Unitaire</th>
                    <th scope="col">Total</th>
                </tr>
            </thead>

            <tbody>
                <tr>
                    <td scope="row">Journées de location</td>
                    <td>{{ days }}</td>
                </tr>
            </tbody>

        </table>
    </div>
{% endblock %}

app/templates/bills/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BillsController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/app/src/Controller/BillsController.php'|file_link(0) }}">src/Controller/BillsController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/app/templates/bills/index.html.twig'|file_link(0) }}">templates/bills/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

app/templates/bills/pdf_template.html.twig
<div class="container">
    <h1>Mon premier pdf</h1>

    <div>
        <h3>Jours de locations</h3>
        <p>p.u : {{ rental.pu }}</p>
        <p>q : {{ rental.quantity }}</p>
        <p>total : {{ rental.pu * rental.quantity }} €</p>
    </div>

    <div>
        <h3>Piscine Adultes</h3>
        <p>p.u : {{ poolAdult.pu }}</p>
        <p>q : {{ poolAdult.quantity }}</p>
        <p>total : {{ poolAdult.pu * poolAdult.quantity }} €</p>
    </div>

    <div>
        <h3>Piscine Enfants</h3>
        <p>p.u : {{ poolKid.pu }}</p>
        <p>q : {{ poolKid.quantity }}</p>
        <p>total : {{ poolKid.pu * poolKid.quantity }} €</p>
    </div>

    <div>
        <h3>TS Adultes</h3>
        <p>p.u : {{ tsAdult.pu }}</p>
        <p>q : {{ tsAdult.quantity }}</p>
        <p>total : {{ tsAdult.pu * tsAdult.quantity }} €</p>
    </div>

    <div>
        <h3>TS Enfants</h3>
        <p>p.u : {{ tskid.pu }}</p>
        <p>q : {{ tskid.quantity }}</p>
        <p>total : {{ tskid.pu * tskid.quantity }} €</p>
    </div>


</div>